# Generated by Django 4.2 on 2023-04-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='doc_link',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='doc_type',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
