# Generated by Django 4.2 on 2023-04-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='core.doctype'),
        ),
    ]
