# Generated by Django 4.2 on 2023-04-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
